### ISSUE TITLE
convert midi file to csv

### ISSUE THREAD

**Issue by wzk1015** [slSeanWU/mir20_eval#2]
I want to evaluate midi files with your repo, but the csv format in `testdata/symbolic` confuses me. How should I convert midi (or remi/cp) into the required csv format? Is there a script to do so?

**Comment by slSeanWU** [comment]
Hi, if you happen to have your pieces in the REMI format defined by our Jazz Transformer, then you can use the `event_to_encodings()` funtion in https://github.com/slSeanWU/jazz_transformer/blob/master/src/convert_to_remi.py to produce the required csv.

Unfortunately, since our original dataset (WJazzD) is not in MIDI format, we didn't write/provide the utilities which work with raw MIDIs. But you can try this: https://github.com/YatingMusic/compound-word-transformer/blob/main/dataset/Dataset.md to convert your MIDIs into REMI.

Hope this helps!

**Comment by wzk1015** [comment]
I will try that. Thanks a lot!

**Comment by MarcusLee-awsome** [comment]
> I will try that. Thanks a lot!

我想问一下您生成了响应的csv文件了吗？您可以教我一下怎么做到吗？怎么从midi转到csv？
期待您的回复。

**Comment by Wangxh-07** [comment]
@wzk1015 您好，请教一下怎么样才能将midi转为这里需要的csv呢？非常感谢

**Comment by wzk1015** [comment]
> Hi, if you happen to have your pieces in the REMI format defined by our Jazz Transformer, then you can use the `event_to_encodings()` funtion in https://github.com/slSeanWU/jazz_transformer/blob/master/src/convert_to_remi.py to produce the required csv.
> 
> Unfortunately, since our original dataset (WJazzD) is not in MIDI format, we didn't write/provide the utilities which work with raw MIDIs. But you can try this: https://github.com/YatingMusic/compound-word-transformer/blob/main/dataset/Dataset.md to convert your MIDIs into REMI.
> 
> Hope this helps!



Hi, if you happen to have your pieces in the REMI format defined by our Jazz Transformer, then you can use the event_to_encodings() funtion in https://github.com/slSeanWU/jazz_transformer/blob/master/src/convert_to_remi.py to produce the required csv.

Unfortunately, since our original dataset (WJazzD) is not in MIDI format, we didn't write/provide the utilities which work with raw MIDIs. But you can try this: https://github.com/YatingMusic/compound-word-transformer/blob/main/dataset/Dataset.md to convert your MIDIs into REMI.

Hope this helps!

**Comment by wzk1015** [comment]
> @wzk1015 您好，请教一下怎么样才能将midi转为这里需要的csv呢？非常感谢

Hi, if you happen to have your pieces in the REMI format defined by our Jazz Transformer, then you can use the event_to_encodings() funtion in https://github.com/slSeanWU/jazz_transformer/blob/master/src/convert_to_remi.py to produce the required csv.

Unfortunately, since our original dataset (WJazzD) is not in MIDI format, we didn't write/provide the utilities which work with raw MIDIs. But you can try this: https://github.com/YatingMusic/compound-word-transformer/blob/main/dataset/Dataset.md to convert your MIDIs into REMI.

Hope this helps!

**Comment by Wangxh-07** [comment]
@wzk1015 我已经转换得到了remi的pkl,请问下一步需要怎么做呢？再次感谢
![image](https://user-images.githubusercontent.com/61005954/167568548-a49cc38c-5169-412d-b0c9-d3c7affdd7a0.png)

**Comment by Wangxh-07** [comment]
![image](https://user-images.githubusercontent.com/61005954/167568820-d317d936-e68e-41f6-98ef-92ab2a916362.png)

@wzk1015 我已经转换得到了remi的pkl,请问下一步需要怎么做呢？event_to_encodings()怎么根据pkl选择传入参数呢？再次感谢！

**Comment by borishanzju** [comment]
同问，得到了remi的pkl，下一步怎么借用event_to_encodings()方法进行生成csv
